import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import adminApi from '@/config/adminApi';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Fetch general details for dynamic metadata
async function getGeneralDetails() {
  try {
    const response = await adminApi.get('/general-details');
    return response.data;
  } catch (error) {
    console.error('Error fetching general details:', error);
    return null;
  }
}

export async function generateMetadata(): Promise<Metadata> {
  const details = await getGeneralDetails();
  
  if (!details) {
    return {
      title: "Portfolio - programmer ikram",
      description: "Generated by create next app",
      icons: {
        icon: "/favicon.ico",
      },
    };
  }

  return {
    title: details.seoDetails?.metaTitle || "Portfolio - programmer ikram",
    description: details.seoDetails?.metaDescription || "Generated by create next app",
    keywords: details.seoDetails?.metaKeywords || [],
    icons: {
      icon: details.siteDetails?.logo || "/favicon.ico",
    },
    openGraph: {
      title: details.seoDetails?.metaTitle || "Portfolio - programmer ikram",
      description: details.seoDetails?.metaDescription || "Generated by create next app",
      images: [details.seoDetails?.ogImage || "/images/og-image.jpg"],
    },
    twitter: {
      card: "summary_large_image",
      title: details.seoDetails?.metaTitle || "Portfolio - programmer ikram",
      description: details.seoDetails?.metaDescription || "Generated by create next app",
      images: [details.seoDetails?.ogImage || "/images/og-image.jpg"],
      creator: details.seoDetails?.twitterHandle || "@yourusername",
    },
  };
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
              style={{padding:0, margin: 0}}

        className={`${geistSans.variable} ${geistMono.variable} antialiased body`}
      >
        {children}
      </body>
    </html>
  );
}
